### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dgcurtis** [simianAstronaut/pi-hole-visualizer#2]
I tried running dns_stats.py but I'm getting this error message:

Initiating connection with server.
Successful connection with server.
Traceback (most recent call last):
  File "./dns_stats.py", line 435, in <module>
    main()
  File "./dns_stats.py", line 431, in main
    event_loop(args, pw_hash)
  File "./dns_stats.py", line 360, in event_loop
    args.randomize)
  File "./dns_stats.py", line 97, in bar_chart_vertical
    domain_min = interval_data[0][0]
IndexError: list index out of range

**Comment by simianAstronaut** [comment]
Your Pi-hole server is returning incomplete data. Are queries currently being generated and received on your network?

**Comment by dgcurtis** [comment]
Yes, dns queries are being answered by the pihole and data is being populated in the pihole gui.

It's a fresh install of pihole (as of yesterday) but I decided to re-run the gravity update.  I restarted the dns_stats service afterwards and now the sense is displaying the info.

Looks like things are fine now.

Thanks!
