### ISSUE TITLE
Not every Animation Shows Up

### ISSUE THREAD

**Issue by XeroShi** [simianAstronaut/pi-hole-visualizer#3]
I realized when I got the program running and checking out everything. I realized that one or few of the animations don't really show up instead the HAT goes blank for a few seconds before going to the next one. Is this Normal? 
Edit: I also noticed a difference from running it from terminal than when it Starts up: 
Running the Script shows the first 3 animations
Running from the start shows the Wifi Icon, Spiral Chart, and the Horizontal Bar Graph.

**Comment by simianAstronaut** [comment]
This is normal behavior.

To view the other charts, authorization from the Pi-hole web server is required. If you are running Pi-hole Visualizer on the same machine that is running Pi-hole, it is assumed a configuration file containing the password hash is located at (/etc/pihole/setupVars.conf) and no action is required.
If you are on a remote machine, you can enable authorization by creating an environment variable containing the password hash. Append the following line to (~/.bash_profile) or (~/.profile): export WEBPASSWORD="hash_value".

Hopefully this solves your issue.

**Comment by XeroShi** [comment]
Yeah Im running the Program on the same machine as the Pi Hole  but still

**Comment by simianAstronaut** [comment]
Have you set up a password for the admin interface?

**Comment by XeroShi** [comment]
Yeah.

**Comment by simianAstronaut** [comment]
The configuration file located at /etc/pihole/setupVars.conf should look something like this:
```
TEMPERATUREUNIT=F
WEBUIBOXEDLAYOUT=boxed
WEBPASSWORD=b3689d5b0d6c500600878b55fe667d1973eabf4b91b6e0dd39ef2e982682315f
DHCP_START=192.168.1.2
DHCP_END=192.168.1.199
DHCP_ROUTER=192.168.1.1
DHCP_LEASETIME=744
PIHOLE_DOMAIN=fSociety
DHCP_IPv6=true
DHCP_ACTIVE=false
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=192.168.1.200/24
IPV6_ADDRESS=2600:6c55:7900:1c5:0:a8:eb7f:a189
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
DNSMASQ_LISTENING=local
PIHOLE_DNS_1=127.0.0.1#5353
DNS_FQDN_REQUIRED=false
DNS_BOGUS_PRIV=false
DNSSEC=true
CONDITIONAL_FORWARDING=true
CONDITIONAL_FORWARDING_IP=192.168.1.1
CONDITIONAL_FORWARDING_DOMAIN=fSociety
CONDITIONAL_FORWARDING_REVERSE=1.168.192.in-addr.arpa
Examine: VERSE=1.168.192.in-addr.arpa

```
You should have a hash value representing your admin interface password after the 'WEBPASSWORD='. The program simply passes this as a query parameter to the web server for authorization.

**Comment by XeroShi** [comment]
Oohh! Alright! After a few minutes of looking at the HAT I saw that the 2nd animation popped up!
